services:
  app:
    build: .
    container_name: app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - main
    ports:
      - "8000:8000"
    reset:
      always
    volumes:
      - .:/app
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    networks:
      - main
    reset:
      always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    networks:
      - main
    reset:
      always
    ports:
      - "6379:6379"

networks:
  main:

volumes:
  postgres_data: